import { AuctionCategoryType } from "@/interface/auction-list";

export const NPC_NAME: string[] = [
  "델",
  "델렌",
  "상인 라누",
  "상인 피루",
  "모락",
  "상인 아루",
  "리나",
  "상인 누누",
  "상인 메루",
  "켄",
  "귀넥",
  "얼리",
  "데위",
  "테일로",
  "상인 세누",
  "상인 베루",
  "상인 에루",
  "상인 네루",
  "카디",
  "인장 상인",
  "피오나트",
];

export const SERVER_NAME: string[] = ["류트", "만돌린", "하프", "울프"];

export enum AuctionCategoryEnum {
  MeleeEquipment = "근거리 장비",
  RangedEquipment = "원거리 장비",
  MagicEquipment = "마법 장비",
  Armor = "갑옷 장비",
  DefenseEquipment = "방어 장비",
  Accessories = "액세서리",
  SpecialEquipment = "특수 장비",
  Installations = "설치물",
  EnchantSupplies = "인챈트 용품",
  Scrolls = "스크롤",
  MagicraftSupplies = "마기그래프 용품",
  Books = "서적",
  Consumables = "소모품",
  Totems = "토템",
  CraftingMaterials = "생활 재료",
  Others = "기타",
}

export const AUCTION_CATEGORY: AuctionCategoryType | any = {
  [AuctionCategoryEnum.MeleeEquipment]: [
    "한손 장비",
    "양손 장비",
    "검",
    "도끼",
    "둔기",
    "랜스",
    "핸들",
    "너클",
    "체인 블레이드",
  ],
  [AuctionCategoryEnum.RangedEquipment]: [
    "활",
    "석궁",
    "듀얼건",
    "수리검",
    "아틀라틀",
    "원거리 소모품",
  ],
  [AuctionCategoryEnum.MagicEquipment]: [
    "실린더",
    "스태프",
    "원드",
    "마도서",
    "오브",
  ],
  [AuctionCategoryEnum.Armor]: ["중갑옷", "경갑옷", "천옷"],
  [AuctionCategoryEnum.DefenseEquipment]: [
    "장갑",
    "신발",
    "모자/가발",
    "방패",
    "로브",
  ],
  [AuctionCategoryEnum.Accessories]: ["얼굴 장식", "액세서리", "꼬리", "날개"],
  [AuctionCategoryEnum.SpecialEquipment]: [
    "악기",
    "생활 도구",
    "마리오네트",
    "에코스톤",
    "에이도스",
    "팔리아스 유물",
    "기타 장비",
  ],
  [AuctionCategoryEnum.Installations]: ["의자/사물", "낭만농장/달빛섬"],
  [AuctionCategoryEnum.EnchantSupplies]: ["인챈트 스크롤", "마법가루"],
  [AuctionCategoryEnum.Scrolls]: ["도면", "옷본", "마족 스크롤", "기타 스크롤"],
  [AuctionCategoryEnum.MagicraftSupplies]: [
    "마기그래프",
    "마기그래프 도안",
    "기타 재료",
  ],
  [AuctionCategoryEnum.Books]: ["책", "마비노벨", "페이지"],
  [AuctionCategoryEnum.Consumables]: [
    "포션",
    "음식",
    "허브",
    "던전 통행증",
    "알반 훈련석",
    "개조석",
    "보석",
    "변신 메달",
    "염색 앰플",
    "스케치",
    "핀즈비즈",
    "기타 소모품",
  ],
  [AuctionCategoryEnum.Totems]: ["토템"],
  [AuctionCategoryEnum.CraftingMaterials]: [
    "주머니",
    "천옷/방직",
    "제련/블랙스미스",
    "힐웬 공학",
    "매직 크래프트",
  ],
  [AuctionCategoryEnum.Others]: [
    "제스처",
    "말풍선 스티커",
    "피니 펫",
    "불타래",
    "퍼퓸",
    "분양 메달",
    "뷰티 쿠폰",
    "기타",
  ],
};